# This file is used to manage some global settings for your test project. 
# This file must be valid YAML
# You can read about YAML syntax here: http://www.ansibleworks.com/docs/YAMLSyntax.html
# This YAML checker may come in handy too: http://yamllint.com/
# *********************************************************************************************

---
Production: "http://qa.medicare.gov/DialysisFacilityCompare/"
QA: "http://qa.medicare.gov/DialysisFacilityCompareNew/"
CWSLampDev: "http://medicare-lampdev.cgifederal.com/dialysisfacilitycompare/"
CWSLamp: "http://medicare-lamp.cgifederal.com/dialysisfacilitycompare/"
CWSLampPAS: "http://medicare-lamp.cgifederal.com/dialysisfacilitycompare/"
Local: "http://localhost:9000/"
Itb2: "http://medicare-iterationb2-test.cgifederal.com/dialysisfacilitycompare/"
MyMedicare: "https://mymedicare.gov/"

Physician: "http://medicare.gov/physiciancompare/search.html"
PlanFinder: "http://medicare.gov/find-a-plan/questions/medigap-home.aspx/"
PlanFinder2: "http://medicare-iterationb1-test.cgifederal.com/find-a-plan/questions/home.aspx"

TestEnv: