# This file is used to manage paths to the various pages in the your application. 
# Paths set here can be refered to by their name in steps such as:
#             Given I am on the "form" page
#                      OR
#             Then I should be redirected to the "other" page
# Both "form" and "other" in these examples are looked up in this file during test case execution. 
# If they are not found, the test case will fail.
# You can provide both full URLs and relative paths in this file. For example, you can point to external links
# like this:
# google_maps: http://maps.google.com
# When providing URLs, you must provide the full URL (including http or https)
# In most cases though, it makes more sense to simply provide a relative path like:
#  search: '/search.html'
# If the current environment is set to:
#  Production: 'http://medicare.gov'
# Then the "search" page in this example is understood to be
#   'http://medicare.gov/search.html'
# This file must be valid YAML
# You can read about YAML syntax here: http://www.ansibleworks.com/docs/YAMLSyntax.html
# This YAML checker may come in handy too: http://yamllint.com/
# *********************************************************************************************

---
# PECOS
PECOSLogin: 'http://ffx-pecos-srv02:9080/pecosai/login.action'
PECOSWelcome: 'http://ffx-pecos-srv02:9080/pecosai/welcome.action'
PECOSBaseSearch: 'http://ffx-pecos-srv02:9080/pecosai/baseSearch.action'

PECOShome: 'http://hpmsbeta-web/app/Login.aspx'

# Medicare.Gov
MedicareGovHome: 'http://qa.medicare.gov'
Medicare404: 'http://qa.medicare.gov/hospitalcompare/results.html#loc=22033&lat=38.8735614&lng=-77.3898602'
PHYHome: 'http://www.medicare.gov/physiciancompare/search.html'
NurHome: 'http://medicare-iterationb2-test.cgifederal.com/NursingHomeCompare'

UPLDHome: 'https://www.sendspace.com/'
forgotUsername: 'https://mymedicare.gov/forgotsigninid.aspx'
CMSTestUpload: 'http://cmstestframework.herokuapp.com/form/page'
MedicalLossRatio: 'http://hpmsbeta-web/app/MLRNet/MLRHome.aspx?PI=142800000000'
PhysicianHome: 'http://medicare.gov/physiciancompare/search.html'