# This file is used to manage selectors for the test project.
# Selectors are used to look up specific elements in the HTML page.
#
# An element can be anything enclosed in a valid HTML tag, for example:
# <div id="map"></div> is an element and so is:
# <a href="http://www.medicare.gov">Medicare.gov</a> or even an entire table like:
# <table>...lots of table rows and data ....</table> is an an element (with lots of elements inside it)
#
# When performing tests it is sometimes useful to be able to refer to a specific element.
# In most cases you can do this by referencing the Name or the label of the element. For example:
# to click a button with the name "Search" you can simply write a step:
#
# And I click on the "Search" button
#
#  and this will work on most web pages without any special set up. The framework here is making an intelligent guess
#  about what you mean based on some common web standards. Sometimes these guesses are not accurate (like when you have two Search buttons on the same page) or worse the framework
#  just refuses to guess (when attributes like name, id or label are not correctly set in the DOM). In such cases you would need to specify a selector in this file.
#
# For example in the step:
#
#  Then I should see "correct results" within "ResultsTable"
#
# You might have to first set up a selector called "ResultsTable" in this file.
# You can set up selectors using xpath or a css selector. For a better understanding of
# xpath try: http://www.w3schools.com/xpath/ and
# css selectors: http://www.w3schools.com/cssref/css_selectors.asp
#
# It is always preferred to use the CSS selectors where possible. CSS Selectors are faster and work better with resource constrained mobile devices.
# You can add a css selector for a table element in the web page:
# <table id='resultsTable'>....</table>
# like this:
# ResultsTable: "css:table#resultsTable"
#
# If you need to use xpath then for the same table element it will be:
# ResultsTable: "xpath:/html/body/table[@id='resultsTable']"
#
# Chrome is probably the easiest browser to get css selectors and xpath from.
# Especially with plugins like these: https://chrome.google.com/webstore/search-extensions/css%20selector (open URL in Chrome)
#
# This file must be valid YAML
# You can read about YAML syntax here: http://www.ansibleworks.com/docs/YAMLSyntax.html
# This YAML checker may come in handy too: http://yamllint.com/
# *********************************************************************************************

---
row4Stars: "css: #resultsTable > div.table-responsive > table > tbody > tr:nth-child(4) > td:nth-child(2) > div"
thridStar: "css: #resultsTable > div.table-responsive > table > tbody > tr:nth-child(1) > td:nth-child(2) > div > div > span:nth-child(3)"
fourthdot: "css: #resultsTable > div.table-responsive > table > tbody > tr:nth-child(4) > td:nth-child(2) > div > div > span:nth-child(5)"
################################# Hilarion's Selectors

CMSLink: "css:#cmsli > a"
Medicarelogo: "css:#brand > img"
MedicareYoulink: "css:#helpfulLinksList > li:nth-child(11) > a"
MedicareFooterlogo: "css:#footer-address-img"
MapModifyResultsSection: "css:#tab-modify-results > div"
FooterGo: "css:#footer-go-button"

################################# End

BottomCompareNowButton: "css:#resultsCompareTopButton"
CountyDropDown: "css:#select-facility-county"
DistanceTextBox: "css:#input-facility-distance"
ResultsTable: "#resultsTable"
ResultsCompareTopPanel: "css:#resultsCompareTop"
ResultsCompareBottomPanel: "css:#resultsCompareBottom"
ResultsTableDialysisFacilityInformationColumn: "css:#sid_1"
ResultsTableDistanceColumn: "css:#sid_12"
ResultsTableHomeHemodialysisTrainingColumn: "css:#sid_11"
ResultsTableInCenterHemodialysisColumn: "css:#sid_8"
ResultsTablePeritonealDialysisColumn: "css:#sid_10"
ResultsTableShiftsStartingAfter5PMColumn: "css:#sid_7"
SearchResultsContent: "css:#summaryText"
StateDropDown: "css:#select-facility-state"
TopCompareNowButton: "css:#resultsCompareTopButton"
ZipCodeCityStateOrStateTextBox: "css:#input-facility-location"
DFIResultsPageToolTip: "css:#resultsTable > div.table-responsive > table > thead > tr > th:nth-child(2) > span > a.tooltip-info > span"
DistanceResultsPageToolTip: "css:#resultsTable > div.table-responsive > table > thead > tr > th:nth-child(3) > span > a.tooltip-info > span"
SSAFPResultsPageToolTip: "#css:resultsTable > div.table-responsive > table > thead > tr > th:nth-child(4) > span > a.tooltip-info > span"
ICHNOHSResultsPageToolTip: "css:#resultsTable > div.table-responsive > table > thead > tr > th:nth-child(5) > span > a.tooltip-info > span"
PDResultsPageToolTip: "css:#resultsTable > div.table-responsive > table > thead > tr > th:nth-child(6) > span > a.tooltip-info > span"
HHTResultsPageToolTip: "css:#resultsTable > div.table-responsive > table > thead > tr > th:nth-child(7) > span > a.tooltip-info > span"
SearchResultsSection: "css:#search-results-section"
StarratingToolTipresults: "css:#resultsTable > div.table-responsive > table > thead > tr > th:nth-child(2) > span > span.pushed.pull-left > a.tooltip-info.col-xs-12.col-sm-12.col-md-12.text-center.push-up-ten > span"
ResultsTableRatingsColumn: "css:#sid_13"
Firststar: "css:#resultsTable > div.table-responsive > table > tbody > tr:nth-child(1) > td:nth-child(2) > div > div > span:nth-child(1) > i.fa.fa-star-o.fa-stack-1x"
Secondstar: "css:#resultsTable > div.table-responsive > table > tbody > tr:nth-child(1) > td:nth-child(2) > div > div > span:nth-child(2) > i.fa.fa-star-o.fa-stack-1x"
Thirdstar: "css:#resultsTable > div.table-responsive > table > tbody > tr:nth-child(1) > td:nth-child(2) > div > div > span:nth-child(3)"
Fourthstar: "css:#resultsTable > div.table-responsive > table > tbody > tr:nth-child(1) > td:nth-child(2) > div > div > span:nth-child(4)"
Fifthstar: "css:#resultsTable > div.table-responsive > table > tbody > tr:nth-child(1) > td:nth-child(2) > div > div > span:nth-child(5)"
Learnmoreaboutstarratings: "css:#link_Map"
ProfileGenInfotooltip: "css:#tabs-1 > div.container-sm-height > div > div.col-md-5.col-sm-height.border-right > b > a > span"
BestTreatmentPracticestab: "css:#ui-id-38"
Printallresultslist: "css:#printAllLink"
BestTreatmentPracticestab: "css:#ui-id-38"
VAsearchADCP: "css:#pid_492635"
ProBesttreatmentpractices: "css:#ui-id-13"
ProHospitalizationsanddeath: "css:#ui-id-14"
Gotomapview: "css:#results-side-column > div.panel.hidden-xs > button"
GoToListView: "css:#results-tabs > div.panel.hidden-xs > button"
DialysisFacilityInformationmap: "css:#sid_1"
NextPagemap: "css:#resultsTable > div:nth-child(1) > ul > li:nth-child(8) > a > em"
page3mapbutton: "css:#resultsTable > div:nth-child(1) > ul > li:nth-child(5) > a"
Firstpagemap: "css:#resultsTable > div:nth-child(1) > ul > li:nth-child(1) > a > em"
Lastpagemap: "css:#resultsTable > div:nth-child(1) > ul > li:nth-child(9) > a > em"  
BestTreatmentPracticestab: "css: #results > ul > li:nth-child(2)"
HospitalDeathtab: "css: #results > ul > li:nth-child(3)"
Hemoglobin: "css:#ui-accordion-3-header-0"
Transfusions: "css: #ui-accordion-4-header-0"
DialysisAdequacy: "css: #ui-accordion-5-header-0"
VascularAccess: "css: #ui-accordion-6-header-0"
MineralBone: "css: #ui-accordion-7-header-0"
Modifyyoursearch: "css: #ui-id-148"

#Mymedicare selectors
Myhealthtab: "css:html#htmlHead.FFX body.WIN.smallFont form#formMyMedicare div#OverallMedicareContainer div#page header#header nav#topnav ul#nav-list.MSP li.top.sub a"
Mymedicarelogo: "css:#cobrand > img"
Expandcollapseicon: "css:#ui-accordion-2-header-0 > span"
ManuallyaddDFCbtn: "css:#results-side-column > div.panel.panel-default.hidden-xs > div > button:nth-child(1)"
FavDilaysisFacilityInformationHeader: "css:#sid_1"
FavDFCSSA5PMHeader: "css:#sid_7"
FavDFCPDHeader: "css:#sid_10"
FavDFCHHTHeader: "css:#sid_11"
FavDFCICHHeader: "css:#sid_8"

#ResultsPageSelectors
AddToCompare492626: "xpath: //*[@id='492626']"
AddToCompare492615: "xpath: //*[@id='492615']"
AddToCompare492620: "xpath: //*[@id='492620']"
AddToCompare493504: "xpath: //*[@id='493504']"


CheckBoxTop492626: "xpath: //*[@id='492626_chkbox_Top']"
CheckBoxTop492615: "xpath: //*[@id='492615_chkbox_Top']"
CheckBoxTop492620: "xpath: //*[@id='492620_chkbox_Top']"

CheckBoxBottom492626: "xpath: //*[@id='492626_chkbox_Bottom']"
CheckBoxBottom492615: "xpath: //*[@id='492615_chkbox_Bottom']"
CheckBoxBottom492620: "xpath: //*[@id='492620_chkbox_Bottom']"

#QIP Static pages Selectors
QIPAnemia: "css:#left-navs > ul > li > ul > li:nth-child(1) > a"
QIPDialysis: "css:#left-navs > ul > li > ul > li:nth-child(2) > a"
QIPVascular: "css:#left-navs > ul > li > ul > li:nth-child(3) > a"
QIPNHSN: "css:#left-navs > ul > li > ul > li:nth-child(4) > a"
QIPInCenter: "css:#left-navs > ul > li > ul > li:nth-child(5) > a"
QIPMineral: "css:#left-navs > ul > li > ul > li:nth-child(6) > a"
QIPPerfomance: "css:#left-navs > ul > li > ul > li:nth-child(7) > a"


MedicareGovHeader:
  EspanolLink: "xpath://*[@id='navbar-collapse-left']/ul/li[1]/a"
  FontSizerLinks: "css:.visible-md visible-lg"
  EmailLink: "css:#emailli"
  PrintLink: "css:#printli"
  AboutUsLink: "css:#aboutli"
  FAQLink: "css:#FAQli"
  GlossaryLink: "css:#glossaryli"
  MedicareGovLink: "css:.toobarnavli"
  CMSGovLink: "css:#cmsli"
  MyMedicareGovLoginLink: "css:#mymedicareli"
  MedicareGovBanner: "css:#brand"
  DialysisFacilityCompareBanner: "css:#logotitle"
  NavigationTabs: "css:#topnav"

MedicareGovFooter:
  FooterActionBar: "css:#footerActionBar"
  ButtonHomeFooter: "css:#btnHomeFooter"
  HomeButton: "css:#footer-home-btn"
  MedicareGovFooterLogo: "css:#footer-address-img"
  FooterAddress: "css:#footer-address-text"
  FooterHHSLogo: "css:#footer_hhs_logo"
  FooterColumn1: "css:.col-md-6 push-down"
  FooterColumn2: "css:.col-md-6 push-down border-right"
  FooterColumn3: "css:.col-md-5 push-down border-right"
  FooterColumn4: "css:.col-md-7 push-down"
  
